# Change these first
owner: buildbuddy-io # Your GitHub organization or username, where this repository lives
repo: buildbuddy-uptime # The name of this repository

sites:
  - name: BuildBuddy Cloud
    url: https://app.buildbuddy.io
  - name: BuildBuddy Website
    url: https://www.buildbuddy.io
  - name: BuildBuddy Documentation
    url: https://docs.buildbuddy.io
  - name: BuildBuddy Blog
    url: https://blog.buildbuddy.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.buildbuddy.io
  faviconSvg: https://docs.buildbuddy.io/img/favicon_black.svg
  # baseUrl: /your-repo-name
  logoUrl: https://docs.buildbuddy.io/img/logo.svg
  name: BuildBuddy
  introTitle: "**BuildBuddy** is an open-core Bazel build event viewer, result store, remote cache, and remote build execution platform."
  introMessage: This page provides status information on the services that are part of BuildBuddy Cloud. Check back here to view the current status of the services listed below. If you are experiencing an issue not listed here, please [contact Support](mailto:support@buildbuddy.io). 
  navbar:
    - title: Status
      href: /
    - title: Home
      href: http://www.buildbuddy.io/
    - title: Docs
      href: http://docs.buildbuddy.io/
    - title: Blog
      href: http://blog.buildbuddy.io/
    - title: Slack
      href: http://slack.buildbuddy.io/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
