owner: buildbuddy-io # Your GitHub organization or username, where this repository lives
repo: buildbuddy-uptime # The name of this repository

sites:
  - name: BuildBuddy Cloud
    url: https://app.buildbuddy.io
  - name: BuildBuddy Website
    url: https://www.buildbuddy.io
  - name: BuildBuddy Documentation
    url: https://docs.buildbuddy.io
  - name: BuildBuddy Blog
    url: https://blog.buildbuddy.io

status-website:
  cname: status.buildbuddy.io
  faviconSvg: https://docs.buildbuddy.io/img/favicon_black.svg
  logoUrl: https://docs.buildbuddy.io/img/logo.svg
  # themeUrl: https://status.buildbuddy.io/buildbuddy-theme.css
  name: ""
  introTitle: "**BuildBuddy** System Status"
  introMessage: >
    This page provides status information on the services that are part of BuildBuddy Cloud.
    Check back here to view the current status of the services listed below.
    If you are experiencing an issue not listed here, please [contact Support](mailto:support@buildbuddy.io).
    To subscribe to status updates in Slack, use ```/github subscribe buildbuddy-io/buildbuddy-status issues```. See https://github.com/integrations/slack.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: "© 2020 Iteration, Inc."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
